apiVersion: v1
kind: Service
metadata:
  name: mongo-configsvr
  namespace: ecommerce
spec:
  clusterIP: None
  selector:
    app: mongo-configsvr
  ports:
    - port: 27019
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-configsvr
  namespace: ecommerce
spec:
  serviceName: mongo-configsvr
  replicas: 1
  selector:
    matchLabels:
      app: mongo-configsvr
  template:
    metadata:
      labels:
        app: mongo-configsvr
    spec:
      containers:
        - name: mongo-configsvr
          image: mongo:4.4
          command:
            - mongod
            - --configsvr
            - --replSet=csrs
            - --port=27019
            - --keyFile=/etc/mongo-keyfile/mongodb-keyfile
            - --bind_ip_all
          ports:
            - containerPort: 27019
          resources:
            requests: { memory: "192Mi", cpu: "100m" }
            limits: { memory: "384Mi", cpu: "500m" }
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: keyfile
              mountPath: /etc/mongo-keyfile
              readOnly: true
      volumes:
        - name: keyfile
          secret:
            secretName: mongo-keyfile
            defaultMode: 0400
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 512Mi