spring:
  datasource:
    url: jdbc:postgresql://postgres-payment:5432/payment_service
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://user-service:8081/.well-known/jwks.json

server:
  port: 8082