spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-platform?currentSchema=user_service
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: user_service
  security:
    jwt:
      private-key-location: classpath:keys/local-private.pem
      public-key-location: classpath:keys/local-public.pem

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/