spring:
  main:
    banner-mode: off
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    jwt:
      private-key-location: ${SECURITY_JWT_PRIVATE_KEY_LOCATION}
      public-key-location: ${SECURITY_JWT_PUBLIC_KEY_LOCATION}
      access-expiration: ${SECURITY_JWT_ACCESS_EXPIRATION:600}
      refresh-expiration: ${SECURITY_JWT_REFRESH_EXPIRATION:86400}

server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info