spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-platform
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secretKey: 123
      accessExpiration: 50400
      refreshExpiration: 50400