CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fullname   VARCHAR(128)                            NOT NULL,
    email      VARCHAR(64)                             NOT NULL UNIQUE,
    username   VARCHAR(32)                             NOT NULL UNIQUE,
    password   VARCHAR(256)                            NOT NULL,
    role       VARCHAR(16)                             NOT NULL,
    active     BOOLEAN                                 NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP                               NOT NULL,
    updated_at TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);