spring:
  main:
    banner-mode: off
  application:
    name: product-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SECURITY_JWT_JWKS_URI}
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9083}

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

app:
  internal:
    api-key: ${INTERNAL_API_KEY}